apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Du-devBR/pipelinebr-gitops.git
    targetRevision: main
    path: enviroment/dev/infra/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
